name: deploy_installer

on:
  workflow_dispatch: # 手動実行用

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install CLASP
        run: npm install -g @google/clasp

      - name: Create clasp credentials
        run: |
          cat <<EOF > ~/.clasprc.json
          {
            "token": {
              "refresh_token": "${{ secrets.REFRESH_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/drive.file",
              "token_type": "Bearer",
              "expiry_date": 9999999999999
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}"
            },
            "isLocalCreds": true
          }
          EOF

      - name: Copy backend.js to installer directory
        run: |
          # backend.jsをinstallerディレクトリにコピー
          cp webapp/backend.js installer/backend.js
          echo "backend.jsをinstallerディレクトリにコピーしました"

      - name: Create & Push Bound Apps Script
        run: |
          # installerディレクトリに移動
          cd installer

          # スプレッドシートに紐づくApps Scriptプロジェクトを作成
          clasp create --title "家計簿入力支援ツール" --parentId "${{ secrets.TARGET_SPREADSHEET_ID }}"

          # コードをpush
          clasp push -f

          echo "新しい家計簿入力支援ツールがインストールされました。古い家計簿入力支援ツールプロジェクトは削除してください。"