name: deploy_webapp

on:
  workflow_dispatch: # 手動実行用

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install CLASP
        run: npm install -g @google/clasp

      - name: Create clasp credentials
        run: |
          cat <<EOF > ~/.clasprc.json
          {
            "token": {
              "refresh_token": "${{ secrets.REFRESH_TOKEN }}",
              "scope": "https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/drive.file",
              "token_type": "Bearer",
              "expiry_date": 9999999999999
            },
            "oauth2ClientSettings": {
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}"
            },
            "isLocalCreds": true
          }
          EOF

      - name: Push & Update Apps Script
        run: |
          # webappディレクトリに移動
          cd webapp

          # コードを push
          clasp push -f

          # 既存デプロイを更新
          clasp deploy --deploymentId ${{ secrets.CLASP_DEPLOYMENT_ID }}

      - name: Set Master Spreadsheet ID
        run: |
          # webappディレクトリに移動
          cd webapp

          # GitHub SecretsからマスタスプレッドシートIDを取得してスクリプトプロパティに設定
          clasp run setMasterSpreadsheetId --params '["${{ secrets.TARGET_SPREADSHEET_ID }}"]'
